name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"


jobs:
  srcinfo:
    name: srcinfo
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/action-archlinux@v2

      - name: gg
        run: cat /etc/os-release