name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"


jobs:
  srcinfo:
    name: srcinfo
    runs-on: ubuntu-latest
    steps:
      - uses: enkodin/action-archlinux@v1
      - name: Test
        run: cat /etc/os-releases
