name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"


jobs:
  srcinfo:
    name: srcinfo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo ${{ env.paths }}

      - name: Test
        uses: actions/action-archlinux@v2
        run: cat /etc/os-release