name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"
  workflow_dispatch:


jobs:

  makepkg:
    name: makepkg
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: prepare
        id: prepare
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"

      - name: debug
        run: echo "${{ steps.prepare.outputs.modified }}"

      - name: printsrc
        uses: enkodin/action-archlinux-makepkg@v1
        with:
          cmd: "--printsrc"
          package: "ddnsc"
