name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"
  workflow_dispatch:


jobs:

  makepkg:
    name: makepkg
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - id: files
        name: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: printsrc
        uses: enkodin/action-archlinux-makepkg@v1
        with:
          cmd: "--printsrc"
          pkgbuilds: ${{ steps.files.outputs.added_modified }}
