name: aur-push

on:
  push:
    paths:
      - "*/PKGBUILD"
  workflow_dispatch:


jobs:
  srcinfo:
    name: srcinfo
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Print
        uses: enkodin/action-archlinux-makepkg@v1
        with:
          cmd: "--arg"
