name: version-check

on:
  schedule:
    - cron: "0 * * * *"


jobs:

  nvmchecker:
    name: nvmchecker
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: check
        run: echo "running"